### ISSUE TITLE
[Bug] I can't access the configs in fabric 1.21

### ISSUE THREAD

**Issue by TBNRSonicMax** [BloCamLimb/ModernUI#254] opened 2024-11-23 08:12 UTC
I can't access the configs in fabric 1.21

**Comment by BloCamLimb** [comment] 2024-11-23 10:35
Please stop spamming.

You must provide detailed information according to our issue template. If you are unsure if this is a bug or a known issue, please discuss it on our Discord.

**Comment by BloCamLimb** [comment] 2024-12-09 16:11
I think this is a duplicate of #240

**Closed by BloCamLimb** 2024-12-09 16:11 UTC
