### ISSUE TITLE
[Bug] Buggy Interaction Between ModernUI and Emojiful

### ISSUE THREAD

**Issue by SalmonSays** [BloCamLimb/ModernUI#47] opened 2021-01-22 09:29 UTC
**Describe the bug**
ModernUI and Emojiful (https://www.curseforge.com/minecraft/mc-mods/emojiful) produce extra section signs "§" and garbage text in Tooltips and the Main Menu

**To Reproduce**
1) Install Forge 36.0.01 on Minecraft 1.16.5
2) Download/add "ModernUI-1.16.5-2.4.1.76-universal.jar" to mods folder
2) Download/add "emojiful-1.16.4-2.1.2.jar" to mods folder

**Expected behavior**
Tooltips should be clean and uncluttered, free of unusual and unnecessary characters.

**Screenshots**

![wzetwFk](https://user-images.githubusercontent.com/11697389/105472365-76d22a00-5c61-11eb-8500-9e24023c5edc.png)
![gTJaPIY](https://user-images.githubusercontent.com/11697389/105472366-776ac080-5c61-11eb-9a4e-70986911b086.png)

**Environment**
 - Mod Version: "ModernUI-1.16.5-2.4.1.76-universal.jar"
 - Forge Version: 36.0.01
 - Operating System: Windows 10 19042
 - Graphics Card: Nvidia RTX 2080ti
 - Other Mods: "emojiful-1.16.4-2.1.2.jar"

https://github.com/InnovativeOnlineIndustries/Emojiful/issues/18

**Comment by EnterFor** [comment] 2021-01-25 08:12
https://github.com/InnovativeOnlineIndustries/Emojiful/issues/16
Somehow, we have both installed, but the problem is very different...

**Comment by Brittank88** [comment] 2021-05-19 06:26
A partial solution is to set `globalRenderer = false` in ModernUI's `client.toml`. This fixed the issues for me, though of course, you will lose the smooth font. You get to keep the cool UI elements it adds, and the GUI background blur effect, though.

**Comment by EnterFor** [comment] 2022-01-06 10:33
Has the problem been solved?

**Comment by Brittank88** [comment] 2022-01-08 09:14
Apart from my imperfect fix, no, the author has never done anything about this issue that I can see. They would have closed it otherwise.

**Comment by Ashley123477** [comment] 2022-02-16 02:49
This issue still hasnt been resolved

**Comment by Brittank88** [comment] 2022-06-25 05:33
That doesn't seem like a fix as much as a bandaid but sure I guess.

**Closed** 2023-08-11 07:12 UTC
Labels: conflict, extension, no solution
