### ISSUE TITLE
[Bug]: Crash on startup with Modern UI+Debugify+Fabric Waystones on MC 1.20.1

### ISSUE THREAD

**Issue by victorguima** [BloCamLimb/ModernUI#183] opened 2023-10-28 01:11 UTC
**Describe the bug**
Minecraft crashes on startup with Debufiy+Modern UI+Fabric Waystones and their dependencies

**To Reproduce**
Start the game with that modlist.

All relevant information is in the crash report: https://pastebin.com/sYxY0vPP

**Comment by BloCamLimb** [comment] 2023-10-28 05:01
Duplicate of https://github.com/BloCamLimb/ModernUI/issues/170

Debugify fixed a Minecraft bug for EditBox, but Modern UI also fixed this bug when providing Unicode support for EditBox. Then you have to open debugify jar file as zip archive, open `debugify.client.mixins.json` and delete the line `"basic.mc140646.EditBoxMixin",`.

Note: this bug was fixed in Minecraft 1.20.2, so Modern UI will not crash in 1.20.2 with Debugify.

**Comment by BloCamLimb** [comment] 2023-11-06 06:57
We fixed the compatibility in 3.9.0

**Closed** 2023-11-10 10:01 UTC
Labels: duplicate
